### ISSUE TITLE
TODO

### ISSUE THREAD

**Issue by lrusak** [OpenELEC/OpenELEC.tv#4079]
There are various TODO's left around, I don't want them to be forgotten ;) 

Also, this is probably a better place to track them then in the TODO file.

- [x] [busybox - 98-busybox.conf](https://github.com/OpenELEC/OpenELEC.tv/blob/master/packages/sysutils/busybox/profile.d/98-busybox.conf#L24)
- [x] [busybox - fs-resize](https://github.com/OpenELEC/OpenELEC.tv/blob/master/packages/sysutils/busybox/scripts/fs-resize#L54)
- [x] [eventlircd - ircore.evmap](https://github.com/OpenELEC/OpenELEC.tv/blob/master/packages/sysutils/eventlircd/evmap/ircore.evmap#L41)
- [x] [libressl - package.mk](https://github.com/OpenELEC/OpenELEC.tv/blob/master/packages/security/libressl/package.mk#L39)
- [x] [xf86-video-intel - package.mk](https://github.com/OpenELEC/OpenELEC.tv/blob/master/packages/x11/driver/xf86-video-intel/package.mk#L60)
- [x] [libva - package.mk](https://github.com/OpenELEC/OpenELEC.tv/blob/master/packages/multimedia/libva/package.mk#L46)
- [x] [kodi - kodi-config](https://github.com/OpenELEC/OpenELEC.tv/blob/master/packages/mediacenter/kodi/scripts/kodi-config#L22)
- [x] [kodi - package.mk - visualizations](https://github.com/OpenELEC/OpenELEC.tv/blob/master/packages/mediacenter/kodi/package.mk#L89)
- [x] [kodi - package.mk - lto](https://github.com/OpenELEC/OpenELEC.tv/blob/master/packages/mediacenter/kodi/package.mk#L322)
- [x] [kodi - package.mk - xbmc compatibility](https://github.com/OpenELEC/OpenELEC.tv/blob/master/packages/mediacenter/kodi/package.mk#L423)
- [x] [scripts - unpack](https://github.com/OpenELEC/OpenELEC.tv/blob/master/scripts/unpack#L58)
- [x] [scripts - build](https://github.com/OpenELEC/OpenELEC.tv/blob/master/scripts/build#L357)
- [x] [systemd - package.mk](https://github.com/OpenELEC/OpenELEC.tv/blob/master/packages/sysutils/systemd/package.mk#L235)
- [x] [installer - Get "msdos" or "gpt"](https://github.com/OpenELEC/OpenELEC.tv/blob/master/packages/tools/installer/scripts/installer#L556)
- [x] [installer - show the setupmenu](https://github.com/OpenELEC/OpenELEC.tv/blob/master/packages/tools/installer/scripts/installer#L643)
- [x] [installer - show the logfile](https://github.com/OpenELEC/OpenELEC.tv/blob/master/packages/tools/installer/scripts/installer#L649)

From TODO:
- [ ] irserver: - rework irserver/init.d for systemd
- [ ] settings addon: - remove ps3 sleep? should be fixed in bluez 5.13/5.14

**Comment by stefansaraev** [comment]
those are not forgotten. but well. done
/TODO I wont touch.
